const editorDefaults = {
  copy: {
    'nav-logo': 'TOMSUN',
    'nav-works': '作品介绍',
    'nav-about': '个人档案',
    'hero-meta-name': '孙泽豪 / TOM SUN',
    'hero-meta-role': '视觉传达 · AI 影像',
    'hero-meta-place': '2026',
    'contact-eyebrow': 'CONTACT / 合作联系',
    'contact-title': '让下一个作品从一次对话开始。',
    'fact-a-desc': 'Post-05 Serial Entrepreneur',
    'fact-a-title': '05 后持续创业者',
    'fact-b-desc': 'Animation Creator & Director',
    'fact-b-title': '动画创作者 · 导演',
    'fact-c-desc': 'Certified Creator by Xin pian chang Shotlab',
    'fact-c-title': 'AIGC 认证创作人',
    'hero-desc': '这里是孙泽豪的个人作品集入口。完整自我介绍、视频作品与项目细节置于后续页面中',
    'hero-eyebrow': 'PORTFOLIO ENTRANCE BY ZEHAO SUN / 孙泽豪视觉作品集',
    'hero-title': '让视觉成为作品被记住的语言',
    'hero-desc-v3': '这里收录视觉设计、AI 动画与电影感影像实验',
    'hero-eyebrow-v3': '孙泽豪视觉作品集 / PORTFOLIO ARCHIVE',
    'hero-title-line-1': '视觉叙事',
    'hero-title-line-2': '与',
    'hero-title-line-3': '实验档案',
    'intro-desc-a':
      '孙泽豪，2005年11月生于山东青岛，湖南农业大学视觉传达本科在读。2025年5月加入字节跳动&湖南大学校企合作智能美学项目组，个人总计完成1,000+人工智能图像及视频的质检标注工作。中央美术学院美术学专业校考合格、湖南省大学生公益广告大赛平面设计类全省一等奖、新片场认证创作人、Uidea首届AI创作大赛入围。',
    'intro-desc-b':
      '我关注如何在画面当中建立情绪，也关注作品如何被记住。从视觉传达、品牌系统到 AI 动画，我希望把设计从单张画面推进到可观看、可感知、可传播的完整体验。',
    'intro-eyebrow': 'DIRECTOR BIOGRAPHY / 自我介绍',
    'intro-title': '一个多元创作者',
    'intro-desc-a-v3':
      '孙泽豪，2005年11月生于山东青岛，湖南农业大学视觉传达本科在读。2025年5月加入字节跳动&湖南大学校企合作智能美学项目组，个人总计完成1,000+人工智能图像及视频的质检标注工作。中央美术学院美术学专业校考合格、湖南省大学生公益广告大赛平面设计类全省一等奖、新片场认证创作人、Uidea首届AI创作大赛入围。',
    'intro-title-v3': '一个多元创作者',
    'project-0-title': 'AI 影像实验',
    'project-0-type': 'AI Animation / Moving Image',
    'project-1-title': '品牌视觉系统',
    'project-1-type': 'Branding / Visual Identity',
    'project-2-title': '数字体验设计',
    'project-2-type': 'UI/UX / Interactive Design',
    'strength-0-desc': '把概念、镜头、节奏和情绪组织成有记忆点的画面。',
    'strength-0-title': '视觉叙事',
    'strength-1-desc': '将 AIGC 工作流用于影像生成、动态分镜和实验短片。',
    'strength-1-title': 'AI 动画',
    'strength-2-desc': '从标志、字体、色彩到应用系统，建立统一视觉语言。',
    'strength-2-title': '品牌设计',
    'strength-3-desc': '兼顾作品气质与实际交付，把灵感推进成可展示成果。',
    'strength-3-title': '执行落地',
    'strengths-eyebrow': 'CAPABILITIES / 个人优势',
    'strengths-title': '视觉设计师、AI 动画设计师、品牌设计师。',
    'video-0-desc':
      '当前主作品视频，包含视觉叙事、镜头调度、AI 影像实验与导演意识。后续可以替换为正式项目标题、封面和完整项目说明。',
    'video-0-title': '成片 / Main Showreel',
    'video-0-type': 'AI Animation · Visual Direction',
    'video-1-title': '只是想再听一次你的声音',
    'video-1-type': 'AI 影像 / 情绪氛围叙事',
    'video-2-title': '既见未来，为何不拜',
    'video-2-type': 'AI 动画 / 东方神话实验',
    'video-3-title': '灵感无界',
    'video-3-type': '航拍影像 / 运动视觉实验',
    'video-main-desc':
      '当前主作品视频，包含视觉叙事、镜头调度、AI 影像实验与导演意识。后续可以替换为正式项目标题、封面和完整项目说明。',
    'video-main-title': '成片 / Main Showreel',
    'video-main-type': 'AI Animation · Visual Direction',
    'video-wukong-desc': '万象皆虚，唯有眼前的因果不灭。当凡躯瞥见未来的那一瞬，是该跪地俯首，还是挥棒破障？',
    'video-wukong-title': '既见未来，为何不拜',
    'video-wukong-type': 'AI 动画 / 东方神话实验',
    'video-drone-desc': '镜头掠过田野、水渠与地平线，速度把现实拉成一条流动的轨迹。它不是单纯的风景记录，而是一段关于视野被打开的运动影像。',
    'video-drone-title': '灵感无界',
    'video-drone-type': '航拍影像 / 运动视觉实验',
    'video-wind-desc': '一座低温的街区，一场迟迟没有停下的雨，以及远处像记忆一样压来的巨浪。作品讲的不是灾难，而是某个再也无法抵达的声音。',
    'video-wind-title': '只是想再听一次你的声音',
    'video-wind-type': 'AI 影像 / 情绪氛围叙事',
    'video-main-desc-v3':
      '在无人的澳大利亚红土荒原上，一个机械袋鼠头机器人带着一台旧留声机驶向海边。它不懂爱，却把一首歌带到了海边。',
    'video-wukong-desc-v3':
      '万象皆虚，唯有眼前的因果不灭。当凡躯瞥见未来的那一瞬，是该跪地俯首，还是挥棒破障？',
    'video-drone-desc-v3':
      '镜头掠过田野、水渠与地平线，速度把现实拉成一条流动的轨迹。它不是单纯的风景记录，而是一段关于视野被打开的运动影像。',
    'video-wind-desc-v3':
      '一座低温的街区，一场迟迟没有停下的雨，以及远处像记忆一样压来的巨浪。作品讲的不是灾难，而是某个再也无法抵达的声音。',
    'video-desc':
      '这里已经预留好后续作品展厅结构。你给我正式封面、标题和介绍之后，每个视频都可以继续扩展成独立项目页。',
    'video-eyebrow': 'VIDEO WORKS / 视频作品',
    'video-title': '点击作品卡片，进入不同影像项目。',
    'work-eyebrow': 'SELECTED WORK / 精选项目',
    'work-title': '作品封面先占位，后续替换为你的高清作品图。',
    'divider-01-title': '先看影像，再进入档案',
    'divider-01-text': '四支短片构成作品集主叙事：红土、神话、农田与抒情。每个作品都是一个独立章节。',
    'divider-02-title': '作品是一条轨道',
    'divider-02-text': '向下滚动时，作品会像胶片一样横向推进。点击任意作品进入完整项目档案。',
    'divider-03-text': '简历信息已收束成策展标签，包含真实经历。',
    'contact-kicker': 'CONTACT / 2026',
    'contact-title': '让我们从一次对话开始',
    'contact-email': 'QDSZH@OUTLOOK.COM +86 159 5326 9399',
  },
  style: {
    'nav-brand': { x: 22, y: 0, size: null },
    'hero-eyebrow-v3': { x: 67, y: -26, size: 16 },
    'hero-title-line-2': { x: 11, y: 104, size: 58 },
    'hero-title-line-3': { x: 45, y: 32, size: 120 },
    'hero-desc-v3': { x: 63, y: -12, size: 18 },
    'divider-01-title': { x: -23, y: -1, size: 62 },
    'divider-02-text': { x: 0, y: 0, size: 18 },
    'about-kicker': { x: 0, y: 0, size: 16 },
    'intro-title-v3': { x: 0, y: 0, size: 108 },
    'intro-desc-a-v3': { x: 0, y: 0, size: 17 },
    'contact-kicker': { x: 3, y: -68, size: 22 },
    'contact-title': { x: 0, y: -45, size: 110 },
    'contact-email': { x: 14, y: 0, size: 16 },
    'work-drone-title': { x: -6, y: 0, size: null },
  },
  box: {
    'contact-eyebrow': { scale: 100, x: 0, y: 0 },
    'contact-title': { scale: 100, x: 0, y: 0 },
    'fact-a-desc': { scale: 100, x: 0, y: 0 },
    'fact-a-title': { scale: 100, x: 0, y: 0 },
    'fact-b-desc': { scale: 100, x: 0, y: 0 },
    'fact-b-title': { scale: 100, x: 0, y: 0 },
    'fact-c-desc': { scale: 100, x: 0, y: 0 },
    'fact-c-title': { scale: 100, x: 0, y: 0 },
    'hero-desc': { scale: 100, x: 0, y: 0 },
    'hero-eyebrow': { scale: 85, x: 0, y: -23 },
    'hero-title': { scale: 100, x: 0, y: -3 },
    'intro-desc-a': { scale: 100, x: 0, y: 0 },
    'intro-desc-b': { scale: 100, x: 0, y: 0 },
    'intro-eyebrow': { scale: 105, x: 0, y: -5 },
    'intro-title': { scale: 95, x: -1, y: -6 },
    'project-0-title': { scale: 100, x: 0, y: 0 },
    'project-0-type': { scale: 100, x: 0, y: 0 },
    'project-1-title': { scale: 100, x: 0, y: 0 },
    'project-1-type': { scale: 100, x: 0, y: 0 },
    'project-2-title': { scale: 100, x: 0, y: 0 },
    'project-2-type': { scale: 100, x: 0, y: 0 },
    'strength-0-desc': { scale: 100, x: 0, y: 0 },
    'strength-0-title': { scale: 100, x: 0, y: 0 },
    'strength-1-desc': { scale: 100, x: 0, y: 0 },
    'strength-1-title': { scale: 100, x: 0, y: 0 },
    'strength-2-desc': { scale: 100, x: 0, y: 0 },
    'strength-2-title': { scale: 100, x: 0, y: 0 },
    'strength-3-desc': { scale: 100, x: 0, y: 0 },
    'strength-3-title': { scale: 100, x: 0, y: 0 },
    'strengths-eyebrow': { scale: 100, x: 0, y: 0 },
    'strengths-title': { scale: 100, x: 0, y: 0 },
    'video-0-desc': { scale: 100, x: 0, y: 0 },
    'video-0-title': { scale: 100, x: 0, y: 0 },
    'video-0-type': { scale: 100, x: 0, y: 0 },
    'video-1-title': { scale: 100, x: 0, y: 0 },
    'video-1-type': { scale: 100, x: 0, y: 0 },
    'video-2-title': { scale: 100, x: 0, y: 0 },
    'video-2-type': { scale: 100, x: 0, y: 0 },
    'video-3-title': { scale: 100, x: 0, y: 0 },
    'video-3-type': { scale: 100, x: 0, y: 0 },
    'video-desc': { scale: 100, x: 0, y: 0 },
    'video-eyebrow': { scale: 100, x: 0, y: 0 },
    'video-title': { scale: 100, x: 0, y: 0 },
    'work-eyebrow': { scale: 100, x: 0, y: 0 },
    'work-title': { scale: 100, x: 0, y: 0 },
  },
  media: {
    'intro-portrait-full': {
      scale: 165,
      src: '/assets/tom-portrait-full.jpg',
      x: 38,
      y: -57,
    },
  },
};

export default editorDefaults;
